<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32998" started-at="2019-10-22T04:29:20Z" finished-at="2019-10-22T04:29:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32998" started-at="2019-10-22T04:29:20Z" finished-at="2019-10-22T04:29:53Z">
      <class name="com.torenzo.qa.testcases.LoginPageTest">
        <test-method status="PASS" signature="launchApp()[pri:0, instance:com.torenzo.qa.testcases.LoginPageTest@3c0ecd4b]" name="launchApp" is-config="true" duration-ms="11768" started-at="2019-10-22T09:59:20Z" finished-at="2019-10-22T09:59:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method status="FAIL" signature="loginVerifyTest()[pri:0, instance:com.torenzo.qa.testcases.LoginPageTest@3c0ecd4b]" name="loginVerifyTest" duration-ms="18970" started-at="2019-10-22T09:59:31Z" finished-at="2019-10-22T09:59:50Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.torenzo.qa.util.TestUtil.readDataFromExcellString(TestUtil.java:31)
	at com.torenzo.qa.pages.LoginPage.passCreadentilas(LoginPage.java:88)
	at com.torenzo.qa.testcases.LoginPageTest.loginVerifyTest(LoginPageTest.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginVerifyTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.torenzo.qa.testcases.LoginPageTest@3c0ecd4b]" name="tearDown" is-config="true" duration-ms="2240" started-at="2019-10-22T09:59:50Z" finished-at="2019-10-22T09:59:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.torenzo.qa.testcases.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
