<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Torenzo" name="com.torenzo.qa.pomtest.GuestPageTest" tests="10" failures="0" timestamp="1 Nov 2019 11:11:51 GMT" time="227.796" errors="1">
  <testcase name="deleteGuestWindowTest" time="4.627" classname="com.torenzo.qa.pomtest.GuestPageTest"/>
  <testcase name="addOneGuestTest" time="31.962" classname="com.torenzo.qa.pomtest.GuestPageTest"/>
  <testcase name="addMoreGuestTest" time="8.313" classname="com.torenzo.qa.pomtest.GuestPageTest"/>
  <testcase name="addNightinGuestTest" time="31.179" classname="com.torenzo.qa.pomtest.GuestPageTest"/>
  <testcase name="zeroGuestWindowTest" time="6.877" classname="com.torenzo.qa.pomtest.GuestPageTest"/>
  <testcase name="cancelGuestWindowTest" time="27.507" classname="com.torenzo.qa.pomtest.GuestPageTest"/>
  <testcase name="addGuestToOrder" time="34.923" classname="com.torenzo.qa.pomtest.GuestPageTest"/>
  <testcase name="deleteGuestFromOrderTest" time="6.019" classname="com.torenzo.qa.pomtest.GuestPageTest">
    <error type="java.lang.AssertionError" message="All option are enabled even aftre having guest more than one expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: All option are enabled even aftre having guest more than one expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at com.torenzo.qa.pomtest.GuestPageTest.deleteGuestFromOrderTest(GuestPageTest.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- deleteGuestFromOrderTest -->
  <testcase name="verfiyHomePageTest" time="34.634" classname="com.torenzo.qa.pomtest.GuestPageTest"/>
  <testcase name="deleteGuestFromOrderByLongPressTest" time="41.755" classname="com.torenzo.qa.pomtest.GuestPageTest"/>
</testsuite> <!-- com.torenzo.qa.pomtest.GuestPageTest -->
